### ISSUE TITLE
falling behind & stalls during streaming

### ISSUE THREAD

**Issue by edsu** [edsu/twarc#62]
During high volume events Twitter's streaming API can [send warnings](https://dev.twitter.com/streaming/overview/request-parameters#stallwarnings) when you are falling behind. It would be useful to ask for these, log them, and act accordingly. It might be important to decouple json parsing from writing the data so that things move faster. Also, maybe we could accept gzip from the API?

We also need to make sure that we guard against [stalls](https://dev.twitter.com/streaming/overview/connecting), which are periods of > 90 seconds if no data is received.

**Comment by remagio** [comment]
imho: could be better have gzip enable with an option when starting twarc. Being useful with low volume having json unzipped

**Comment by edsu** [comment]
I don't really understand what gzip has to do with this ticket. If you want to gzip just send the output through gzip?

    twarc.py --search foo | gzip - > tweets.json.gz

Perhaps it would be useful for utils/archive.py though. If that's the case please open another ticket for that.

**Comment by edsu** [comment]
FWIW I was seeing up to 70 tweets/second when archiving #CharlestonShooting and didn't fall behind. But this may have been the result of running on a good connection on Amazon EC2.

**Comment by remagio** [comment]
- I misunderstood the meaning of your "Also, maybe we could accept gzip from the API?" when remembering one of your past question about: "what if twarc result *.json.gz instead .json" :-)
- I wrote on another issues that since a while --stream works fine always with huges quantity, I agree. Usually I use too high-end servers on DigitalOcean/Amazon EC2 with best location for loads. And possibly at best tmz when using archive.py.
But for first time I was unable to archive #pride #lovewins. So I missed it

**Comment by edsu** [comment]
This ticket only concerns the streaming API. When using Twitter's search API results are rate limited by Twitter, which is currently handled by twarc.

**Comment by edsu** [comment]
Also would be useful to look for and log [Limit Notices](https://dev.twitter.com/streaming/overview/messages-types#limit_notices).
